/*
 * This file was automatically generated by Apache Tiles Autotag.
 */
package org.apache.tiles.jsp.taglib;

import java.io.IOException;
import java.util.Deque;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.tagext.SimpleTagSupport;

import org.apache.tiles.ListAttribute;
import org.apache.tiles.autotag.core.runtime.ModelBody;
import org.apache.tiles.autotag.core.runtime.AutotagRuntime;
import org.apache.tiles.request.Request;
import org.apache.tiles.template.ComposeStackUtil;

/**
 * <p>
 * <strong>Declare a list that will be pass as an attribute. </strong>
 * </p>
 * <p>
 * Declare a list that will be pass as an attribute . List elements are added
 * using the tag 'addAttribute' or 'addListAttribute'. This tag can only be used
 * inside 'insertTemplate', 'insertDefinition' or 'definition' tag.
 * </p>
 */
public class AddListAttributeTag extends SimpleTagSupport {

    /**
     * The template model.
     */
    private final AddListAttributeModel model = new AddListAttributeModel();

    /**
     * The comma-separated list of roles that can use the list attribute.
     */
    private java.lang.String role;

    /**
     * Getter for role property.
     *
     * @return
     * The comma-separated list of roles that can use the list attribute.
     */
    public java.lang.String getRole() {
        return role;
    }

    /**
     * Setter for role property.
     *
     * @param role
     * The comma-separated list of roles that can use the list attribute.
     */
    public void setRole(java.lang.String role) {
        this.role = role;
    }

    /** {@inheritDoc} */
    @Override
    public void doTag() throws JspException, IOException {
        AutotagRuntime<org.apache.tiles.request.Request> runtime = new org.apache.tiles.request.jsp.autotag.JspAutotagRuntime();
        SimpleTagSupport tag = (SimpleTagSupport) runtime;
        tag.setJspContext(getJspContext());
        tag.setJspBody(getJspBody());
        tag.setParent(getParent());
        tag.doTag();
        org.apache.tiles.request.Request request = runtime.createRequest();
        ModelBody modelBody = runtime.createModelBody();
        model.execute(
            role,
            request, modelBody
        );
    }


    /**
     * <p>
     * <strong>Declare a list that will be pass as an attribute. </strong>
     * </p>
     * <p>
     * Declare a list that will be pass as an attribute . List elements are added
     * using the tag 'addAttribute' or 'addListAttribute'. This tag can only be used
     * inside 'insertTemplate', 'insertDefinition' or 'definition' tag.
     * </p>
     *
     * @version $Rev: 1305937 $ $Date: 2012-03-28 05:15:15 +1100 (Wed, 28 Mar 2012) $
     * @since 2.2.0
     */
    public static class AddListAttributeModel {

        /**
         * Executes the model.
         *
         * @param role The comma-separated list of roles that can use the list attribute.
         * @param request The request.
         * @param modelBody The body.
         * @throws IOException If the body cannot be evaluated.
         */
        public void execute(String role, Request request, ModelBody modelBody) throws IOException {
            Deque<Object> composeStack = ComposeStackUtil.getComposeStack(request);
            ListAttribute listAttribute = new ListAttribute();
            listAttribute.setRole(role);
            composeStack.push(listAttribute);
            modelBody.evaluateWithoutWriting();
            listAttribute = (ListAttribute) composeStack.pop();
            ListAttribute parent = (ListAttribute) composeStack.peek();
            assert parent != null;
            parent.add(listAttribute);
        }
    }

}
