/*
 * This file was automatically generated by Apache Tiles Autotag.
 */
package org.apache.tiles.jsp.taglib;

import java.io.IOException;
import java.util.Deque;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.tagext.SimpleTagSupport;

import org.apache.tiles.Attribute;
import org.apache.tiles.Definition;
import org.apache.tiles.access.TilesAccess;
import org.apache.tiles.autotag.core.runtime.ModelBody;
import org.apache.tiles.autotag.core.runtime.AutotagRuntime;
import org.apache.tiles.autotag.core.runtime.annotation.Parameter;
import org.apache.tiles.mgmt.MutableTilesContainer;
import org.apache.tiles.request.Request;
import org.apache.tiles.template.ComposeStackUtil;

/**
 * <p>
 * <strong>Create a definition at runtime. </strong>
 * </p>
 * <p>
 * Create a new definition at runtime. Newly created definition will be
 * available across the entire request.
 * </p>
 */
public class DefinitionTag extends SimpleTagSupport {

    /**
     * The template model.
     */
    private final DefinitionModel model = new DefinitionModel();

    /**
     * The name of the definition to create. If not specified, an
     * anonymous definition will be created.
     */
    private java.lang.String name;

    /**
     * The template of this definition.
     */
    private java.lang.String template;

    /**
     * A comma-separated list of roles. If present, the definition
     * will be rendered only if the current user belongs to one of the roles.
     */
    private java.lang.String role;

    /**
     * The definition name that this definition extends.
     */
    private java.lang.String extendsParam;

    /**
     * The preparer to use to invoke before the definition is
     * rendered.
     */
    private java.lang.String preparer;

    /**
     * Getter for name property.
     *
     * @return
     * The name of the definition to create. If not specified, an
     * anonymous definition will be created.
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Setter for name property.
     *
     * @param name
     * The name of the definition to create. If not specified, an
     * anonymous definition will be created.
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     * Getter for template property.
     *
     * @return
     * The template of this definition.
     */
    public java.lang.String getTemplate() {
        return template;
    }

    /**
     * Setter for template property.
     *
     * @param template
     * The template of this definition.
     */
    public void setTemplate(java.lang.String template) {
        this.template = template;
    }

    /**
     * Getter for role property.
     *
     * @return
     * A comma-separated list of roles. If present, the definition
     * will be rendered only if the current user belongs to one of the roles.
     */
    public java.lang.String getRole() {
        return role;
    }

    /**
     * Setter for role property.
     *
     * @param role
     * A comma-separated list of roles. If present, the definition
     * will be rendered only if the current user belongs to one of the roles.
     */
    public void setRole(java.lang.String role) {
        this.role = role;
    }

    /**
     * Getter for extends property.
     *
     * @return
     * The definition name that this definition extends.
     */
    public java.lang.String getExtends() {
        return extendsParam;
    }

    /**
     * Setter for extends property.
     *
     * @param extendsParam
     * The definition name that this definition extends.
     */
    public void setExtends(java.lang.String extendsParam) {
        this.extendsParam = extendsParam;
    }

    /**
     * Getter for preparer property.
     *
     * @return
     * The preparer to use to invoke before the definition is
     * rendered.
     */
    public java.lang.String getPreparer() {
        return preparer;
    }

    /**
     * Setter for preparer property.
     *
     * @param preparer
     * The preparer to use to invoke before the definition is
     * rendered.
     */
    public void setPreparer(java.lang.String preparer) {
        this.preparer = preparer;
    }

    /** {@inheritDoc} */
    @Override
    public void doTag() throws JspException, IOException {
        AutotagRuntime<org.apache.tiles.request.Request> runtime = new org.apache.tiles.request.jsp.autotag.JspAutotagRuntime();
        SimpleTagSupport tag = (SimpleTagSupport) runtime;
        tag.setJspContext(getJspContext());
        tag.setJspBody(getJspBody());
        tag.setParent(getParent());
        tag.doTag();
        org.apache.tiles.request.Request request = runtime.createRequest();
        ModelBody modelBody = runtime.createModelBody();
        model.execute(
            name,
            template,
            role,
            extendsParam,
            preparer,
            request, modelBody
        );
    }


    /**
     * <p>
     * <strong>Create a definition at runtime. </strong>
     * </p>
     * <p>
     * Create a new definition at runtime. Newly created definition will be
     * available across the entire request.
     * </p>
     *
     * @version $Rev: 1305937 $ $Date: 2012-03-28 05:15:15 +1100 (Wed, 28 Mar 2012) $
     * @since 2.2.0
     */
    public static class DefinitionModel {

        /**
         * Executes the operation.
         *
         * @param name The name of the definition to create. If not specified, an
         * anonymous definition will be created.
         * @param template The template of this definition.
         * @param role A comma-separated list of roles. If present, the definition
         * will be rendered only if the current user belongs to one of the roles.
         * @param extendsParam The definition name that this definition extends.
         * @param preparer The preparer to use to invoke before the definition is
         * rendered.
         * @param request The request.
         * @param modelBody The body.
         * @throws IOException If something goes wrong.
         * @since 2.2.0
         */
        public void execute(String name, String template, String role,
                            @Parameter(name = "extends") String extendsParam, String preparer,
                            Request request, ModelBody modelBody) throws IOException {
            Deque<Object> composeStack = ComposeStackUtil
                    .getComposeStack(request);
            Definition definition = createDefinition(name, template, role,
                    extendsParam, preparer);
            composeStack.push(definition);
            modelBody.evaluateWithoutWriting();
            MutableTilesContainer container = (MutableTilesContainer) TilesAccess
                    .getCurrentContainer(request);
            definition = (Definition) composeStack.pop();
            registerDefinition(definition, container, composeStack, request);
        }

        /**
         * Creates the definition to store.
         *
         * @param name The name of the definition to create. If not specified, an
         * anonymous definition will be created.
         * @param template The template of this definition.
         * @param role A comma-separated list of roles. If present, the definition
         * will be rendered only if the current user belongs to one of the roles.
         * @param extendsParam The definition name that this definition extends.
         * @param preparer The preparer to use to invoke before the definition is
         * rendered.
         * @return The created definition.
         */
        private Definition createDefinition(String name, String template,
                                            String role, String extendsParam, String preparer) {
            Definition definition = new Definition();
            definition.setName(name);
            Attribute templateAttribute = Attribute
                    .createTemplateAttribute(template);
            templateAttribute.setRole(role);
            definition.setTemplateAttribute(templateAttribute);
            definition.setExtends(extendsParam);
            definition.setPreparer(preparer);
            return definition;
        }

        /**
         * Registers a definition in the container.
         *
         * @param definition The definition to register.
         * @param container The container into which the definition will be
         * registered.
         * @param composeStack The compose stack,
         * @param request The request.
         */
        private void registerDefinition(Definition definition,
                                        MutableTilesContainer container, Deque<Object> composeStack,
                                        Request request) {
            container.register(definition, request);

            if (composeStack.isEmpty()) {
                return;
            }

            Object obj = composeStack.peek();
            if (obj instanceof Attribute attribute) {
                attribute.setValue(definition.getName());
                if (attribute.getRenderer() == null) {
                    attribute.setRenderer("definition");
                }
            }
        }
    }

}
