/*
 * This file was automatically generated by Apache Tiles Autotag.
 */
package org.apache.tiles.jsp.taglib;

import java.io.IOException;
import java.io.Writer;
import java.util.Deque;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.tagext.SimpleTagSupport;

import org.apache.tiles.Attribute;
import org.apache.tiles.TilesContainer;
import org.apache.tiles.access.TilesAccess;
import org.apache.tiles.autotag.core.runtime.ModelBody;
import org.apache.tiles.autotag.core.runtime.AutotagRuntime;
import org.apache.tiles.autotag.core.runtime.annotation.Parameter;
import org.apache.tiles.request.Request;
import org.apache.tiles.template.AttributeResolver;
import org.apache.tiles.template.ComposeStackUtil;
import org.apache.tiles.template.DefaultAttributeResolver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * <p>
 * <strong> Render the value of the specified template attribute to the current
 * Writer</strong>
 * </p>
 * 
 * <p>
 * Retrieve the value of the specified template attribute property, and render
 * it to the current Writer as a String. The usual toString() conversions is
 * applied on found value.
 * </p>
 */
public class GetAsStringTag extends SimpleTagSupport {

    /**
     * The template model.
     */
    private final GetAsStringModel model
            = new GetAsStringModel();

    /**
     * If <code>true</code>, if an exception happens during
     * rendering, of if the attribute is null, the problem will be ignored.
     */
    private boolean ignore;

    /**
     * The preparer to invoke before rendering the attribute.
     */
    private java.lang.String preparer;

    /**
     * A comma-separated list of roles. If present, the attribute
     * will be rendered only if the current user belongs to one of the roles.
     */
    private java.lang.String role;

    /**
     * The default value of the attribute. To use only if
     * the attribute was not computed.
     */
    private java.lang.Object defaultValue;



    /**
     * The name of the attribute.
     */
    private java.lang.String name;

    /**
     * The attribute to use immediately, if not null.
     */
    private org.apache.tiles.Attribute value;

    /**
     * Getter for ignore property.
     *
     * @return
     * If <code>true</code>, if an exception happens during
     * rendering, of if the attribute is null, the problem will be ignored.
     */
    public boolean isIgnore() {
        return ignore;
    }

    /**
     * Setter for ignore property.
     *
     * @param ignore
     * If <code>true</code>, if an exception happens during
     * rendering, of if the attribute is null, the problem will be ignored.
     */
    public void setIgnore(boolean ignore) {
        this.ignore = ignore;
    }

    /**
     * Getter for preparer property.
     *
     * @return
     * The preparer to invoke before rendering the attribute.
     */
    public java.lang.String getPreparer() {
        return preparer;
    }

    /**
     * Setter for preparer property.
     *
     * @param preparer
     * The preparer to invoke before rendering the attribute.
     */
    public void setPreparer(java.lang.String preparer) {
        this.preparer = preparer;
    }

    /**
     * Getter for role property.
     *
     * @return
     * A comma-separated list of roles. If present, the attribute
     * will be rendered only if the current user belongs to one of the roles.
     */
    public java.lang.String getRole() {
        return role;
    }

    /**
     * Setter for role property.
     *
     * @param role
     * A comma-separated list of roles. If present, the attribute
     * will be rendered only if the current user belongs to one of the roles.
     */
    public void setRole(java.lang.String role) {
        this.role = role;
    }

    /**
     * Getter for defaultValue property.
     *
     * @return
     * The default value of the attribute. To use only if
     * the attribute was not computed.
     */
    public java.lang.Object getDefaultValue() {
        return defaultValue;
    }

    /**
     * Setter for defaultValue property.
     *
     * @param defaultValue
     * The default value of the attribute. To use only if
     * the attribute was not computed.
     */
    public void setDefaultValue(java.lang.Object defaultValue) {
        this.defaultValue = defaultValue;
    }
    /**
     * Getter for name property.
     *
     * @return
     * The name of the attribute.
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Setter for name property.
     *
     * @param name
     * The name of the attribute.
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     * Getter for value property.
     *
     * @return
     * The attribute to use immediately, if not null.
     */
    public org.apache.tiles.Attribute getValue() {
        return value;
    }

    /**
     * Setter for value property.
     *
     * @param value
     * The attribute to use immediately, if not null.
     */
    public void setValue(org.apache.tiles.Attribute value) {
        this.value = value;
    }

    /** {@inheritDoc} */
    @Override
    public void doTag() throws JspException, IOException {
        AutotagRuntime<org.apache.tiles.request.Request> runtime
                = new org.apache.tiles.request.jsp.autotag.JspAutotagRuntime();
        SimpleTagSupport tag = (SimpleTagSupport) runtime;
        tag.setJspContext(getJspContext());
        tag.setJspBody(getJspBody());
        tag.setParent(getParent());
        tag.doTag();
        org.apache.tiles.request.Request request = runtime.createRequest();
        ModelBody modelBody = runtime.createModelBody();
        model.execute(
            ignore,
            preparer,
            role,
            defaultValue,
            null,
            null,
            name,
            value,
            request, modelBody
        );
    }


    /**
     * <p>
     * <strong> Render the value of the specified template attribute to the current
     * Writer</strong>
     * </p>
     *
     * <p>
     * Retrieve the value of the specified template attribute property, and render
     * it to the current Writer as a String. The usual toString() conversions is
     * applied on found value.
     * </p>
     *
     * @version $Rev: 1625204 $ $Date: 2014-09-16 12:21:04 +1000 (Tue, 16 Sep 2014) $
     * @since 2.2.0
     */
    public static class GetAsStringModel {

        /**
         * The logging object.
         */
        private final Logger log = LoggerFactory.getLogger(getClass());

        /**
         * The attribute resolver to use.
         */
        private final AttributeResolver attributeResolver;

        /**
         * Constructor that uses the defaut attribute resolver.
         *
         * @since 3.0.0
         */
        public GetAsStringModel() {
            this(new DefaultAttributeResolver());
        }

        /**
         * Constructor.
         *
         * @param attributeResolver The attribute resolver to use.
         * @since 2.2.0
         */
        public GetAsStringModel(AttributeResolver attributeResolver) {
            this.attributeResolver = attributeResolver;
        }

        /**
         * Executes the operation.
         * @param ignore If <code>true</code>, if an exception happens during
         * rendering, of if the attribute is null, the problem will be ignored.
         * @param preparer The preparer to invoke before rendering the attribute.
         * @param role A comma-separated list of roles. If present, the attribute
         * will be rendered only if the current user belongs to one of the roles.
         * @param defaultValue The default value of the attribute. To use only if
         * the attribute was not computed.
         * @param defaultValueRole The default comma-separated list of roles. To use
         * only if the attribute was not computed.
         * @param defaultValueType The default type of the attribute. To use only if
         * the attribute was not computed.
         * @param name The name of the attribute.
         * @param value The attribute to use immediately, if not null.
         * @param request The request.
         * @param modelBody The body.
         * @throws IOException If an I/O error happens during rendering.
         * @since 2.2.0
         */
        public void execute(boolean ignore, String preparer, String role,
                            Object defaultValue, String defaultValueRole,
                            String defaultValueType, @Parameter(required = true) String name,
                            Attribute value, Request request, ModelBody modelBody)
                throws IOException {
            TilesContainer container = TilesAccess.getCurrentContainer(request);
            Deque<Object> composeStack = ComposeStackUtil.getComposeStack(request);
            Attribute attribute = resolveAttribute(container, ignore, preparer,
                    role, defaultValue, defaultValueRole, defaultValueType, name,
                    value, request);
            if (attribute != null)
                composeStack.push(attribute);

            modelBody.evaluateWithoutWriting();
            container = TilesAccess.getCurrentContainer(request);
            Writer writer = request.getWriter();
            if (attribute != null)
                attribute = (Attribute) composeStack.pop();

            renderAttribute(attribute, container, writer, ignore, request);
        }

        /**
         * Resolves the attribute. and starts the context.
         *
         * @param container The Tiles container to use.
         * @param ignore If <code>true</code>, if an exception happens during
         * rendering, of if the attribute is null, the problem will be ignored.
         * @param preparer The preparer to invoke before rendering the attribute.
         * @param role A comma-separated list of roles. If present, the attribute
         * will be rendered only if the current user belongs to one of the roles.
         * @param defaultValue The default value of the attribute. To use only if
         * the attribute was not computed.
         * @param defaultValueRole The default comma-separated list of roles. To use
         * only if the attribute was not computed.
         * @param defaultValueType The default type of the attribute. To use only if
         * the attribute was not computed.
         * @param name The name of the attribute.
         * @param value The attribute to use immediately, if not null.
         * @param request The request.
         * @return The resolved attribute.
         */
        private Attribute resolveAttribute(TilesContainer container,
                                           boolean ignore, String preparer, String role, Object defaultValue,
                                           String defaultValueRole, String defaultValueType, String name,
                                           Attribute value, Request request) {
            if (preparer != null)
                container.prepare(preparer, request);

            Attribute attribute = attributeResolver.computeAttribute(container,
                    value, name, role, ignore, defaultValue, defaultValueRole,
                    defaultValueType, request);
            container.startContext(request);
            return attribute;
        }

        /**
         * Renders the attribute as a string.
         *
         * @param attribute The attribute to use, previously resolved.
         * @param container The Tiles container to use.
         * @param writer The writer into which the attribute will be written.
         * @param ignore If <code>true</code>, if an exception happens during
         * rendering, of if the attribute is null, the problem will be ignored.
         * @param request The request.
         * @throws IOException If an I/O error happens during rendering.
         */
        private void renderAttribute(Attribute attribute, TilesContainer container,
                                     Writer writer, boolean ignore, Request request)
                throws IOException {
            try {
                if (attribute == null && ignore)
                    return;

                Object value = container.evaluate(attribute, request);
                if(value != null)
                    writer.write(value.toString());

            } catch (IOException | RuntimeException e) {
                if (!ignore)
                    throw e;
                else if (log.isDebugEnabled())
                    log.debug("Ignoring exception", e);

            } finally {
                container.endContext(request);
            }
        }
    }

}
