/*
 * This file was automatically generated by Apache Tiles Autotag.
 */
package org.apache.tiles.jsp.taglib;

import java.io.IOException;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.tagext.SimpleTagSupport;

import org.apache.tiles.Attribute;
import org.apache.tiles.AttributeContext;
import org.apache.tiles.TilesContainer;
import org.apache.tiles.access.TilesAccess;
import org.apache.tiles.autotag.core.runtime.ModelBody;
import org.apache.tiles.autotag.core.runtime.AutotagRuntime;
import org.apache.tiles.autotag.core.runtime.annotation.Parameter;
import org.apache.tiles.request.Request;

/**
 * <p>
 * <strong>Insert a template.</strong>
 * </p>
 * <p>
 * Insert a template with the possibility to pass parameters (called
 * attributes). A template can be seen as a procedure that can take parameters
 * or attributes. <code>&lt;tiles:insertTemplate&gt;</code> allows to define
 * these attributes and pass them to the inserted jsp page, called template.
 * Attributes are defined using nested tag
 * <code>&lt;tiles:putAttribute&gt;</code> or
 * <code>&lt;tiles:putListAttribute&gt;</code>.
 * </p>
 * <p>
 * You must specify <code>template</code> attribute, for inserting a template
 * </p>
 * 
 * <p>
 * <strong>Example : </strong>
 * </p>
 * 
 * <pre>
 * &lt;code&gt;
 *           &lt;tiles:insertTemplate template=&quot;/basic/myLayout.jsp&quot; flush=&quot;true&quot;&gt;
 *              &lt;tiles:putAttribute name=&quot;title&quot; value=&quot;My first page&quot; /&gt;
 *              &lt;tiles:putAttribute name=&quot;header&quot; value=&quot;/common/header.jsp&quot; /&gt;
 *              &lt;tiles:putAttribute name=&quot;footer&quot; value=&quot;/common/footer.jsp&quot; /&gt;
 *              &lt;tiles:putAttribute name=&quot;menu&quot; value=&quot;/basic/menu.jsp&quot; /&gt;
 *              &lt;tiles:putAttribute name=&quot;body&quot; value=&quot;/basic/helloBody.jsp&quot; /&gt;
 *           &lt;/tiles:insertTemplate&gt;
 *         &lt;/code&gt;
 * </pre>
 */
public class InsertTemplateTag extends SimpleTagSupport {

    /**
     * The template model.
     */
    private final InsertTemplateModel model
            = new InsertTemplateModel();

    /**
     * The template to render.
     */
    private java.lang.String template;

    /**
     * The type of the template attribute.
     */
    private java.lang.String templateType;

    /**
     * The expression to evaluate to get the value of the template.
     */
    private java.lang.String templateExpression;

    /**
     * A comma-separated list of roles. If present, the template
     * will be rendered only if the current user belongs to one of the roles.
     */
    private java.lang.String role;

    /**
     * The preparer to use to invoke before the definition is
     * rendered. If specified, it overrides the preparer specified in the
     * definition itself.
     */
    private java.lang.String preparer;

    /**
     * If <code>true</code>, the response will be flushed after the insert.
     */
    private boolean flush;

    /**
     * Getter for template property.
     *
     * @return
     * The template to render.
     */
    public java.lang.String getTemplate() {
        return template;
    }

    /**
     * Setter for template property.
     *
     * @param template
     * The template to render.
     */
    public void setTemplate(java.lang.String template) {
        this.template = template;
    }
    /**
     * Getter for role property.
     *
     * @return
     * A comma-separated list of roles. If present, the template
     * will be rendered only if the current user belongs to one of the roles.
     */
    public java.lang.String getRole() {
        return role;
    }

    /**
     * Setter for role property.
     *
     * @param role
     * A comma-separated list of roles. If present, the template
     * will be rendered only if the current user belongs to one of the roles.
     */
    public void setRole(java.lang.String role) {
        this.role = role;
    }

    /**
     * Getter for preparer property.
     *
     * @return
     * The preparer to use to invoke before the definition is
     * rendered. If specified, it overrides the preparer specified in the
     * definition itself.
     */
    public java.lang.String getPreparer() {
        return preparer;
    }

    /**
     * Setter for preparer property.
     *
     * @param preparer
     * The preparer to use to invoke before the definition is
     * rendered. If specified, it overrides the preparer specified in the
     * definition itself.
     */
    public void setPreparer(java.lang.String preparer) {
        this.preparer = preparer;
    }

    /**
     * Getter for flush property.
     *
     * @return
     * If <code>true</code>, the response will be flushed after the insert.
     */
    public boolean isFlush() {
        return flush;
    }

    /**
     * Setter for flush property.
     *
     * @param flush
     * If <code>true</code>, the response will be flushed after the insert.
     */
    public void setFlush(boolean flush) {
        this.flush = flush;
    }

    /** {@inheritDoc} */
    @Override
    public void doTag() throws JspException, IOException {
        AutotagRuntime<org.apache.tiles.request.Request> runtime
                = new org.apache.tiles.request.jsp.autotag.JspAutotagRuntime();
        SimpleTagSupport tag = (SimpleTagSupport) runtime;
        tag.setJspContext(getJspContext());
        tag.setJspBody(getJspBody());
        tag.setParent(getParent());
        tag.doTag();
        org.apache.tiles.request.Request request = runtime.createRequest();
        ModelBody modelBody = runtime.createModelBody();
        model.execute(
            template,
            templateType,
            templateExpression,
            role,
            preparer,
            flush,
            request, modelBody
        );
    }


    /**
     * <p>
     * <strong>Insert a template.</strong>
     * </p>
     * <p>
     * Insert a template with the possibility to pass parameters (called
     * attributes). A template can be seen as a procedure that can take parameters
     * or attributes. <code>&lt;tiles:insertTemplate&gt;</code> allows to define
     * these attributes and pass them to the inserted jsp page, called template.
     * Attributes are defined using nested tag
     * <code>&lt;tiles:putAttribute&gt;</code> or
     * <code>&lt;tiles:putListAttribute&gt;</code>.
     * </p>
     * <p>
     * You must specify <code>template</code> attribute, for inserting a template
     * </p>
     *
     * <p>
     * <strong>Example : </strong>
     * </p>
     *
     * <pre>
     * &lt;code&gt;
     *           &lt;tiles:insertTemplate template=&quot;/basic/myLayout.jsp&quot; flush=&quot;true&quot;&gt;
     *              &lt;tiles:putAttribute name=&quot;title&quot; value=&quot;My first page&quot; /&gt;
     *              &lt;tiles:putAttribute name=&quot;header&quot; value=&quot;/common/header.jsp&quot; /&gt;
     *              &lt;tiles:putAttribute name=&quot;footer&quot; value=&quot;/common/footer.jsp&quot; /&gt;
     *              &lt;tiles:putAttribute name=&quot;menu&quot; value=&quot;/basic/menu.jsp&quot; /&gt;
     *              &lt;tiles:putAttribute name=&quot;body&quot; value=&quot;/basic/helloBody.jsp&quot; /&gt;
     *           &lt;/tiles:insertTemplate&gt;
     *         &lt;/code&gt;
     * </pre>
     *
     * @version $Rev: 1058106 $ $Date: 2011-01-12 23:22:58 +1100 (Wed, 12 Jan 2011) $
     * @since 2.2.0
     */
    public static class InsertTemplateModel {

        /**
         * Executes the operation.
         * @param template The template to render.
         * @param templateType The type of the template attribute.
         * @param templateExpression The expression to evaluate to get the value of the template.
         * @param role A comma-separated list of roles. If present, the template
         * will be rendered only if the current user belongs to one of the roles.
         * @param preparer The preparer to use to invoke before the definition is
         * rendered. If specified, it overrides the preparer specified in the
         * definition itself.
         * @param flush If <code>true</code>, the response will be flushed after the insert.
         * @param request The request.
         * @param modelBody The body.
         * @throws IOException If something goes wrong.
         * @since 2.2.0
         */
        public void execute(@Parameter(required = true) String template,
                            String templateType, String templateExpression, String role,
                            String preparer, boolean flush, Request request, ModelBody modelBody)
                throws IOException {
            TilesContainer container = TilesAccess.getCurrentContainer(request);
            container.startContext(request);
            modelBody.evaluateWithoutWriting();
            container = TilesAccess.getCurrentContainer(request);
            renderTemplate(container, template, templateType, templateExpression,
                    role, preparer, flush, request);
        }

        /**
         * Renders a template.
         *
         * @param container The container to use.
         * @param template The template to render.
         * @param templateType The type of the template attribute.
         * @param templateExpression The expression to evaluate to get the value of the template.
         * @param role A comma-separated list of roles. If present, the template
         * will be rendered only if the current user belongs to one of the roles.
         * @param preparer The preparer to use to invoke before the definition is
         * rendered. If specified, it overrides the preparer specified in the
         * definition itself.
         * @param flush If <code>true</code>, the response will be flushed after the insert.
         * @param request The request.
         * @throws IOException If something goes wrong.
         */
        private void renderTemplate(TilesContainer container, String template,
                                    String templateType, String templateExpression, String role,
                                    String preparer, boolean flush, Request request) throws IOException {
            try {
                AttributeContext attributeContext = container
                        .getAttributeContext(request);
                Attribute templateAttribute = Attribute.createTemplateAttribute(template,
                        templateExpression, templateType, role);
                attributeContext.setPreparer(preparer);
                attributeContext.setTemplateAttribute(templateAttribute);
                container.renderContext(request);
                if (flush)
                    request.getWriter().flush();

            } finally {
                container.endContext(request);
            }
        }
    }

}
