/*
 * This file was automatically generated by Apache Tiles Autotag.
 */
package org.apache.tiles.jsp.taglib;

import java.io.IOException;
import java.util.Deque;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.tagext.SimpleTagSupport;

import org.apache.tiles.Attribute;
import org.apache.tiles.AttributeContext;
import org.apache.tiles.Expression;
import org.apache.tiles.TilesContainer;
import org.apache.tiles.access.TilesAccess;
import org.apache.tiles.autotag.core.runtime.ModelBody;
import org.apache.tiles.autotag.core.runtime.AutotagRuntime;
import org.apache.tiles.autotag.core.runtime.annotation.Parameter;
import org.apache.tiles.request.Request;
import org.apache.tiles.template.ComposeStackUtil;

/**
 * <p>
 * <strong>Put an attribute in enclosing attribute container tag.</strong>
 * </p>
 * <p>
 * Enclosing attribute container tag can be :
 * <ul>
 * <li>&lt;initContainer&gt;</li>
 * <li>&lt;definition&gt;</li>
 * <li>&lt;insertAttribute&gt;</li>
 * <li>&lt;insertDefinition&gt;</li>
 * <li>&lt;putListAttribute&gt;</li>
 * </ul>
 * (or any other tag which implements the <code>PutAttributeTagParent</code>
 * interface. Exception is thrown if no appropriate tag can be found.
 * </p>
 * <p>
 * Put tag can have following atributes :
 * <ul>
 * <li>name : Name of the attribute</li>
 * <li>value : value to put as attribute</li>
 * <li>type : value type. Possible type are : string (value is used as direct
 * string), template (value is used as a page url to insert), definition (value
 * is used as a definition name to insert), object (value is used as it is)</li>
 * <li>role : Role to check when 'insertAttribute' will be called.</li>
 * </ul>
 * </p>
 * <p>
 * Value can also come from tag body. Tag body is taken into account only if
 * value is not set by one of the tag attributes. In this case Attribute type is
 * "string", unless tag body define another type.
 * </p>
 */
public class PutAttributeTag extends SimpleTagSupport {

    /**
     * The template model.
     */
    private final PutAttributeModel model
            = new PutAttributeModel();

    /**
     * The name of the attribute to put.
     */
    private java.lang.String name;

    /**
     * The value of the attribute. Use this parameter, or
     * expression, or body.
     */
    private java.lang.Object value;

    /**
     * The expression to calculate the value from. Use this
     * parameter, or value, or body.
     */
    private java.lang.String expression;

    /**
     * A comma-separated list of roles. If present, the attribute
     * will be rendered only if the current user belongs to one of the roles.
     */
    private java.lang.String role;

    /**
     * The type (renderer) of the attribute.
     */
    private java.lang.String type;

    /**
     * If <code>true</code> the attribute will be cascaded to all nested attributes.
     */
    private boolean cascade;

    /**
     * Getter for name property.
     *
     * @return
     * The name of the attribute to put.
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * Setter for name property.
     *
     * @param name
     * The name of the attribute to put.
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     * Getter for value property.
     *
     * @return
     * The value of the attribute. Use this parameter, or
     * expression, or body.
     */
    public java.lang.Object getValue() {
        return value;
    }

    /**
     * Setter for value property.
     *
     * @param value
     * The value of the attribute. Use this parameter, or
     * expression, or body.
     */
    public void setValue(java.lang.Object value) {
        this.value = value;
    }

    /**
     * Getter for expression property.
     *
     * @return
     * The expression to calculate the value from. Use this
     * parameter, or value, or body.
     */
    public java.lang.String getExpression() {
        return expression;
    }

    /**
     * Setter for expression property.
     *
     * @param expression
     * The expression to calculate the value from. Use this
     * parameter, or value, or body.
     */
    public void setExpression(java.lang.String expression) {
        this.expression = expression;
    }

    /**
     * Getter for role property.
     *
     * @return
     * A comma-separated list of roles. If present, the attribute
     * will be rendered only if the current user belongs to one of the roles.
     */
    public java.lang.String getRole() {
        return role;
    }

    /**
     * Setter for role property.
     *
     * @param role
     * A comma-separated list of roles. If present, the attribute
     * will be rendered only if the current user belongs to one of the roles.
     */
    public void setRole(java.lang.String role) {
        this.role = role;
    }

    /**
     * Getter for type property.
     *
     * @return
     * The type (renderer) of the attribute.
     */
    public java.lang.String getType() {
        return type;
    }

    /**
     * Setter for type property.
     *
     * @param type
     * The type (renderer) of the attribute.
     */
    public void setType(java.lang.String type) {
        this.type = type;
    }

    /**
     * Getter for cascade property.
     *
     * @return
     * If <code>true</code> the attribute will be cascaded to all nested attributes.
     */
    public boolean isCascade() {
        return cascade;
    }

    /**
     * Setter for cascade property.
     *
     * @param cascade
     * If <code>true</code> the attribute will be cascaded to all nested attributes.
     */
    public void setCascade(boolean cascade) {
        this.cascade = cascade;
    }

    /** {@inheritDoc} */
    @Override
    public void doTag() throws JspException, IOException {
        AutotagRuntime<org.apache.tiles.request.Request> runtime
                = new org.apache.tiles.request.jsp.autotag.JspAutotagRuntime();
        SimpleTagSupport tag = (SimpleTagSupport) runtime;
        tag.setJspContext(getJspContext());
        tag.setJspBody(getJspBody());
        tag.setParent(getParent());
        tag.doTag();
        org.apache.tiles.request.Request request = runtime.createRequest();
        ModelBody modelBody = runtime.createModelBody();
        model.execute(
            name,
            value,
            expression,
            role,
            type,
            cascade,
            request, modelBody
        );
    }

    /**
     * <p>
     * <strong>Put an attribute in enclosing attribute container tag.</strong>
     * </p>
     * <p>
     * Enclosing attribute container tag can be :
     * <ul>
     * <li>&lt;initContainer&gt;</li>
     * <li>&lt;definition&gt;</li>
     * <li>&lt;insertAttribute&gt;</li>
     * <li>&lt;insertDefinition&gt;</li>
     * <li>&lt;putListAttribute&gt;</li>
     * </ul>
     * (or any other tag which implements the <code>PutAttributeTagParent</code>
     * interface. Exception is thrown if no appropriate tag can be found.
     * </p>
     * <p>
     * Put tag can have following atributes :
     * <ul>
     * <li>name : Name of the attribute</li>
     * <li>value : value to put as attribute</li>
     * <li>type : value type. Possible type are : string (value is used as direct
     * string), template (value is used as a page url to insert), definition (value
     * is used as a definition name to insert), object (value is used as it is)</li>
     * <li>role : Role to check when 'insertAttribute' will be called.</li>
     * </ul>
     * </p>
     * <p>
     * Value can also come from tag body. Tag body is taken into account only if
     * value is not set by one of the tag attributes. In this case Attribute type is
     * "string", unless tag body define another type.
     * </p>
     *
     * @version $Rev: 1305937 $ $Date: 2012-03-28 05:15:15 +1100 (Wed, 28 Mar 2012) $
     * @since 2.2.0
     */
    public static class PutAttributeModel {

        /**
         * Executes the operation.
         * @param name The name of the attribute to put.
         * @param value The value of the attribute. Use this parameter, or
         * expression, or body.
         * @param expression The expression to calculate the value from. Use this
         * parameter, or value, or body.
         * @param role A comma-separated list of roles. If present, the attribute
         * will be rendered only if the current user belongs to one of the roles.
         * @param type The type (renderer) of the attribute.
         * @param cascade If <code>true</code> the attribute will be cascaded to all nested attributes.
         * @param request The request.
         * @param modelBody The body.
         * @throws IOException If the body cannot be evaluated.
         * @since 2.2.0
         */
        public void execute(@Parameter(required = true) String name, Object value,
                            String expression, String role, String type, boolean cascade,
                            Request request, ModelBody modelBody) throws IOException {
            Deque<Object> composeStack = ComposeStackUtil.getComposeStack(request);
            Attribute attribute = new Attribute();
            composeStack.push(attribute);
            String currentBody = modelBody.evaluateAsString();
            TilesContainer container = TilesAccess.getCurrentContainer(request);
            attribute = (Attribute) composeStack.pop();
            putAttributeInParent(attribute, container, composeStack, name,
                    value, expression, currentBody, role, type, cascade, request);
        }

        /**
         * Determines the parent and puts the attribute inside it.
         *
         * @param attribute The attribute to put;
         * @param container The Tiles container to use.
         * @param composeStack The composing stack.
         * @param name The name of the attribute to put.
         * @param value The value of the attribute. Use this parameter, or
         * expression, or body.
         * @param expression The expression to calculate the value from. Use this
         * parameter, or value, or body.
         * @param body The body of the tag. Use this parameter, or value, or
         * expression.
         * @param role A comma-separated list of roles. If present, the attribute
         * will be rendered only if the current user belongs to one of the roles.
         * @param type The type (renderer) of the attribute.
         * @param cascade If <code>true</code> the attribute will be cascaded to all nested attributes.
         * @param request The request.
         */
        private void putAttributeInParent(Attribute attribute,
                                          TilesContainer container, Deque<Object> composeStack, String name,
                                          Object value, String expression, String body, String role,
                                          String type, boolean cascade, Request request) {
            AttributeContext attributeContext = null;
            if (!composeStack.isEmpty()) {
                Object obj = composeStack.peek();
                if (obj instanceof AttributeContext ac)
                    attributeContext = ac;

            }
            if (attributeContext == null)
                attributeContext = container.getAttributeContext(request);

            if (value != null)
                attribute.setValue(value);
            else if (attribute.getValue() == null && body != null)
                attribute.setValue(body);

            if (expression != null)
                attribute.setExpressionObject(Expression
                        .createExpressionFromDescribedExpression(expression));

            if (role != null)
                attribute.setRole(role);

            if (type != null)
                attribute.setRenderer(type);


            attributeContext.putAttribute(name, attribute, cascade);
        }
    }

}
