/*
 * This file was automatically generated by Apache Tiles Autotag.
 */
package org.apache.tiles.jsp.taglib;

import java.io.IOException;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.tagext.SimpleTagSupport;

import org.apache.tiles.autotag.core.runtime.AutotagRuntime;

/**
 * Selects a container to be used as the "current" container.
 */
public class SetCurrentContainerTag extends SimpleTagSupport {

    /**
     * The template model.
     */
    private final org.apache.tiles.template.SetCurrentContainerModel model
            = new org.apache.tiles.template.SetCurrentContainerModel();

    /**
     * The key of the container to be used as "current". If
     * <code>null</code>, the default one will be used.
     */
    private java.lang.String containerKey;
    /** {@inheritDoc} */
    @Override
    public void doTag() throws JspException, IOException {
        AutotagRuntime<org.apache.tiles.request.Request> runtime
                = new org.apache.tiles.request.jsp.autotag.JspAutotagRuntime();
        SimpleTagSupport tag = (SimpleTagSupport) runtime;
        tag.setJspContext(getJspContext());
        tag.setJspBody(getJspBody());
        tag.setParent(getParent());
        tag.doTag();
        org.apache.tiles.request.Request request = runtime.createRequest();
        model.execute(
            containerKey,
            request
        );
    }
}
