/*
 * This file was automatically generated by Apache Tiles Autotag.
 */
package org.apache.tiles.jsp.taglib;

import java.io.IOException;

import jakarta.servlet.jsp.JspException;
import jakarta.servlet.jsp.tagext.SimpleTagSupport;

import org.apache.tiles.access.TilesAccess;
import org.apache.tiles.autotag.core.runtime.AutotagRuntime;
import org.apache.tiles.request.Request;

/**
 * Selects a container to be used as the "current" container.
 */
public class SetCurrentContainerTag extends SimpleTagSupport {

    /**
     * The template model.
     */
    private final SetCurrentContainerModel model
            = new SetCurrentContainerModel();

    /**
     * The key of the container to be used as "current". If
     * <code>null</code>, the default one will be used.
     */
    private java.lang.String containerKey;
    /** {@inheritDoc} */
    @Override
    public void doTag() throws JspException, IOException {
        AutotagRuntime<org.apache.tiles.request.Request> runtime
                = new org.apache.tiles.request.jsp.autotag.JspAutotagRuntime();
        SimpleTagSupport tag = (SimpleTagSupport) runtime;
        tag.setJspContext(getJspContext());
        tag.setJspBody(getJspBody());
        tag.setParent(getParent());
        tag.doTag();
        org.apache.tiles.request.Request request = runtime.createRequest();
        model.execute(
            containerKey,
            request
        );
    }


    /**
     * Selects a container to be used as the "current" container.
     *
     * @version $Rev: 1058106 $ $Date: 2011-01-12 23:22:58 +1100 (Wed, 12 Jan 2011) $
     * @since 3.0.0
     */
    public static class SetCurrentContainerModel {

        /**
         * Executes the model.
         *
         * @param containerKey The key of the container to be used as "current". If
         * <code>null</code>, the default one will be used.
         * @param request The request.
         */
        public void execute(String containerKey, Request request) {
            TilesAccess.setCurrentContainer(request, containerKey);
        }
    }

}
